# Generated by Django 4.2.3 on 2023-07-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='start_foun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_id', models.CharField(max_length=20)),
                ('founders_name', models.IntegerField(max_length=20)),
            ],
        ),
    ]
