from django.contrib import admin
from django.urls import path,include
from home import views
urlpatterns = [
    path("", views.index,name='home'),
    path("insert",views.insert,name='insert'),
    path("update",views.update,name='update'),
    path("delete",views.delete,name='delete'),
    path("services",views.services,name='services'),
    path("show",views.show,name='show'),
    path("show1",views.show1,name='show1'),
    path("show2",views.show2,name='show2'),
    path("show3",views.show3,name='show3'),
    path("show4",views.show4,name='show4'),
    path("show5",views.show5,name='show5'),
    path("show6",views.show6,name='show6'),
    path("show7",views.show7,name='show7'),
    path("show8",views.show8,name='show8'),
    path("show9",views.show9,name='show9'),
    path("show10",views.show10,name='show10'),
    path("sh4",views.sh4,name='sh4'),
    path("inser_0",views.inser_0,name='inser_0'),
    path("inser_10",views.inser_10,name='inser_10'),
    path("inser_1",views.inser_1,name='inser_1'),
    path("inser_11",views.inser_11,name='inser_11'),
    path("inser_2",views.inser_2,name='inser_2'),
    path("inser_12",views.inser_12,name='inser_12'),
    path("inser_3",views.inser_3,name='inser_3'),
    path("inser_13",views.inser_13,name='inser_13'),
    path("inser_4",views.inser_4,name='inser_4'),
    path("inser_14",views.inser_14,name='inser_14'),
    path("inser_5",views.inser_5,name='inser_5'),
    path("inser_15",views.inser_15,name='inser_15'),
    path("inser_6",views.inser_6,name='inser_6'),
    path("inser_16",views.inser_16,name='inser_16'),
    path("update_0",views.update_0,name='update_0'),
    path("update_10",views.update_10,name='update_10'),
    path("update_1",views.update_1,name='update_1'),
    path("update_11",views.update_11,name='update_11'),
    path("update_2",views.update_2,name='update_2'),
    path("update_12",views.update_12,name='update_12'),
    path("delete_0",views.delete_0,name='delete_0'),
    path("delete_10",views.delete_10,name='delete_10'),
    path("delete_1",views.delete_1,name='delete_1'),
    path("delete_11",views.delete_11,name='delete_11'),
    path("delete_2",views.delete_2,name='delete_2'),
    path("delete_12",views.delete_12,name='delete_12'),
]
